name: "Component compilation test"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker Images"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-compilation-test:
    runs-on: ubuntu-latest
    container:
      image: "grupoavispa/robocomp:development__dsr__latest"
      options: --user demo

    steps:
      - run: "cd /home/demo/robocomp/tools/cli/robocompdsl/test/autogeneration_tests/test_cdsl/ && python3 test_component_generation.py --no-execution --avoid agmTestCp"
  fail-on-image-fail:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: "exit 1"
