name: "robocompdsl test"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker Images"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  robocomp-dsl-test:
    runs-on: ubuntu-latest
    container:
      image: "grupo-avispa/robocomp:development__dsr__latest"
      options: --user demo

    steps:
      - run: "cd /home/demo/robocomp/tools/cli/robocompdsl/test/ && python3 -m unittest discover -p 'test_*.py'"
  fail-on-image-fail:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: "exit 1"
