name: "Robocomp tools install test"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker Images"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-generation-test:
    runs-on: ubuntu-latest
    container:
      image: "grupoavispa/robocomp:development__dsr__latest"
      options: --user demo

    steps:
      - name: Robocomp tools install
        shell: bash
        working-directory: /home/demo/robocomp/tools/cli/
        run: sudo pip3 install .
      - run: "robocomp --help"
      - run: "rcworkspace --help"
      - run: "rcconfig --help"
      - run: "rcbuild --help"
      - run: "rccd --help"
      - run: "rcrun --help"
      - run: "robocompdsl --help"
      - name: Yaku install
        shell: bash
        working-directory: /home/demo/robocomp/tools/yaku/
        run: sudo pip3 install .
      - run: "yaku --help"
  fail-on-image-fail:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: "exit 1"
